# Generated by Django 4.2.4 on 2023-08-28 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("writer", "0005_rename_classification_article_classification_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="author",
            new_name="author_id",
        ),
    ]
