# Generated by Django 4.2.4 on 2023-08-28 06:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("writer", "0006_rename_author_article_author_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="author_id",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="article",
            old_name="classification_id",
            new_name="classification",
        ),
    ]
