# Generated by Django 4.2.4 on 2023-10-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("writer", "0007_rename_author_id_article_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="tag",
            field=models.ManyToManyField(null=True, to="writer.tag"),
        ),
        migrations.AlterField(
            model_name="classification",
            name="classification_name",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="tag_name",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
